export const LANDING = '/'
export const LOGIN = '/signin'
export const SIGN_UP = '/signup'
export const HOME = '/home'
export const CREATE_PROGRAMME = '/create-prog'
export const PASSWORD_FORGET = '/pw-forget'
